services:
  app:
    image: node-test
    build: 
      context: .
    volumes:
      - ./:/src # mount từ môi trường gốc vào trong để nếu các bạn thay đổi code thì bên trong sẽ tự động cập nhật
    # environment: # phần này ta định nghĩa ở file .env nhé
      # - DB_HOST=${DB_HOST}
      # - DB_NAME=${DB_NAME}
      # - REDIS_HOST=${REDIS_HOST}
      # - REDIS_PORT=${REDIS_PORT}
      # - PORT=${PORT}
    ports:
      - "${PORTPRODUCT}:${PORTPRODUCT}" # phần này ta định nghĩa ở file .env nhé
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA= /var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata


 